### ISSUE TITLE
Cannot buy aerobatics warrior upgrade without doing the wingsuit check (even if you have wingsuit)

### ISSUE THREAD

**Issue by Jacksonbird8237** [minous27/TheMessengerRandomizerMod#14]
I was going to try to do the leashing strat to get the note in searing crags but I realized I could buy the upgrade that helps you do it even though I have wingsuit the upgrade is locked.

**Comment by minous27** [comment]
Correct, this is blocked until you view the cutscene in Grotto. It is currently hard-coded that way...but I bet we can change that. :P
