### ISSUE TITLE
Multiworld? 

### ISSUE THREAD

**Issue by Bokyubi** [minous27/TheMessengerRandomizerMod#31]
Hey! I'm someone who enjoys multiworlds and I just caught wind of your randomizer. Provided you know how to write a few server scripts that send checks, you could integrate this into archieplago! If you do not know what archipelago is, here; https://archipelago.gg/

**Comment by Bokyubi** [comment]
https://docs.google.com/document/d/e/2PACX-1vRLdz7L8PEH2LA6dUFXf7ibPjDnBYO_rLDVdt74fUh41YEbAn2ZTfFVCf9CET7q-OGFjoZEsMl1qnZc/pub this doc explains it much better

**Comment by minous27** [comment]
@Bokyubi I am a huge fan of the idea. I played archipelago a time or two (mostly Lttpr) and once the rando is done I think it would be a lot of fun to add to that infrastructure. 👍

**Comment by alwaysintreble** [comment]
I'm interested in helping with this if that's okay with you, since you've entered beta status now. If it is I can likely get started pretty soon unless you'd prefer to wait until this is in a more complete state.

**Comment by minous27** [comment]
@alwaysintreble I'm okay with that if you wish, I think the mod is in a playable state and should foundationally remain the same.

I am currently handling personal things now (baby incoming! 👶) so I don't suspect I'll be very active for a few weeks to a month at least. Still feel free to mess around with it. I'd LOVE to play this in archipelago multiworlds!

**Comment by alwaysintreble** [comment]
@minous27 Cool, looking forward to it, and congrats on the baby!

**Comment by minous27** [comment]
Thanks to @alwaysintreble for implementing this functionality! Foundational code was merged in this project and also forked to [TheMessengerRandomizerModAP](https://github.com/alwaysintreble/TheMessengerRandomizerModAP). Also check out the [Archipelago page for The Messenger](https://archipelago.gg/games/The%20Messenger/info/en)!
